### ISSUE TITLE
Tag examples consistently 

### ISSUE THREAD

**Issue by splattael** [rrrene/elixir-style-guide#1]
It would be nice to use `# preferred way` and `NOT okay` in _every_ example - if feasible.

Also, the order of the examples should be consistent: first `preferred way` and then `NOT okay`.

WDYT?

**Comment by rrrene** [comment]
Good catch! We should always emphasize the "good parts" first and then reason what's also okay/not so good practise. Will do! :+1:

**Comment by rrrene** [comment]
@splattael did this a while ago, forgot to close the issue. thx again :+1:
