### ISSUE TITLE
Regarding long function signatures with guards

### ISSUE THREAD

**Issue by DanielZendejas** [rrrene/elixir-style-guide#6]
Hi,

First of all thank you very much for the great guide, it really helps to make the code more readable.

After a couple of months writing in Elixir I've found that thanks to its pattern matching capabilities and to the use of guards my function signatures can pass well over the 80 characters (soft) limit. I always end up with these ugly and unreadable clauses. For example:

```elixir
def valid_user?(%User{name: name, age: age, email: email})
  when is_binary(name) and is_integer(age) and age > 0 and is_binary(email)
    and email in @valid_emails do
  true
end
def valid_user?(_), do: false
```

I was looking into some code to find out what a good alternative would be, for example [this line in Credo.Check.CodeHelper](https://github.com/rrrene/credo/blob/master/lib/credo/check/code_helper.ex#L176) or [this line in Ecto's Mongo adapter](https://github.com/michalmuskala/mongodb_ecto/blob/master/lib/mongo_ecto.ex#L459) but wanted to know what was your stance on the subject.

*How do you think large function clauses with guards should be handled?*

If an explicit style for this is achieved then I'd be glad to make a PR for the guide, so maybe someone with the same question as me knows which path to take.

Again thanks a lot for the awesome project and hope to hear anyone's opinion.

**Comment by christopheradams** [comment]
What do you think of this style?

```elixir
def valid_user?(%User{name: name, age: age, email: email})
    when is_binary(name) and is_integer(age) and age > 0 and is_binary(email)
    and email in @valid_emails do
  true
end

def valid_user?(_) do
  false
end
```

(This second function head is not directly relevant to your question; however, another recommended style is that if one of the functions is multi-line, then all of them should be.)

**Comment by elasticdog** [comment]
@christopheradams I like that style, and it also aligns with the recommendations made here: https://github.com/lexmag/elixir-style-guide#guard-clauses

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.
